### ISSUE TITLE
Project Fails to Run Initially Due to Incorrect File Structure and Extensions

### ISSUE THREAD

**Issue by masabinhok** [Ayu-hack/Restaurant-Management-System#1]
**Issue Title: Project Fails to Run Initially Due to Incorrect File Structure and Extensions**

### **Description**
The project doesn't run successfully after forking and cloning the repository due to several issues with file naming conventions and folder structure.

### **Steps to Reproduce**
1. Fork and clone the repository.
2. Try running the project following the provided setup instructions.

### **Expected Outcome**
The project should run without errors after the initial setup.

### **Actual Outcome**
The project fails to run due to:
1. **Incorrect file extensions:** The file `ordercontext.json` should be `ordercontext.jsx`.
2. **Folder structure mismatch:** 
   - According to the imports used, pages and components should reside in the `views` folder. However, the `views` folder is incorrectly named `view`, and `components` is named `component`.
   - Additionally, the `pages` folder is currently placed inside `components`.

### **Suggested Fixes**
1. Rename `ordercontext.json` to `ordercontext.jsx`.
2. Rename `view` to `views` and `component` to `components`.
3. Move `pages` to its correct place within `views`.
4. Rename files and folders to follow industry-standard conventions.

### **Screenshots**
![Screenshot 2024-10-01 184906](https://github.com/user-attachments/assets/8a2cdd8f-0fc5-4b49-a694-2b443e146ad9)
![Screenshot 2024-10-01 184916](https://github.com/user-attachments/assets/ba253667-3026-4cc4-b51c-83898d6b883b)
![Screenshot 2024-10-01 184900](https://github.com/user-attachments/assets/e21aa97b-9b07-4b9c-be4a-f1f70a17b676)

---

**Comment by masabinhok** [comment]
Assign me this issue. I have already fixed these on my local computer.

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

**Comment by masabinhok** [comment]
Sure.
