### ISSUE TITLE
Update to better ReadMe.md file

### ISSUE THREAD

**Issue by dhruvjain23** [Ayu-hack/Restaurant-Management-System#10]
I could provide better readMe.md file which will have enough description for the project with screenshots and functionality description as well as have the information about the contribution guidlines and how to fork etc , all will be included.

Kindly assigns me this issue under Hacktoberfest and hacktoberfest-accepted labels. @Ayu-hack

**Comment by Ayu-hack** [comment]
Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!
