### ISSUE TITLE
add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by kartikey369-ind** [Ayu-hack/Restaurant-Management-System#3]
how about adding CODE_OF_CONDUCT.md

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by kartikey369-ind** [comment]
done please check my pr https://github.com/Ayu-hack/Restaurant-Management-System/pull/4
