### ISSUE TITLE
Missing `hacktoberfest` Topic

### ISSUE THREAD

**Issue by masabinhok** [Ayu-hack/Restaurant-Management-System#7]
**Issue: Missing `hacktoberfest` Topic**

Hi,

I noticed that the repository currently has the labels `hacktoberfest2024` and `hacktoberfest-accepted`, but it doesn't have the `hacktoberfest` topic on the repository itself. Because of this, the repository isn't being recognized as participating in Hacktoberfest 2024 on the official website.

To ensure that contributions are counted towards Hacktoberfest, could you please add the `hacktoberfest` topic to the repository? This would allow contributors to have their pull requests counted for the event.

![image](https://github.com/user-attachments/assets/4c71eec2-aae5-46bd-b23f-278607ea2348)

Thank you for your consideration!

**Comment by masabinhok** [comment]
This issue is meant to be fixed by the maintainer only, and I don't think he is actively participating.

**Comment by Ayu-hack** [comment]
Add the tag. Thank you. 
We have many repos so sometimes it take time to manage.

**Comment by Ayu-hack** [comment]
> Can you assign this to me?

Please find some new issue. 
There is an issue with SQL connection try to fix if possible.
There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by ayushisingla** [comment]
There is an issue with SQL connection try to fix if possible. - I can check that, can you share link?
